#!/bin/sh

if pgrep -x waybar >/dev/null; then
    pkill waybar && hyprctl dispatch exec waybar && makoctl reload && sleep 1 && notify-send -c waybar "Waybar Reload" "Waybar successfully reloaded"
else
    hyprctl dispatch exec waybar && sleep 1 && notify-send -c waybar "Waybar Status" "Waybar successfully started"
fi
