#!/bin/sh

wallpaper_file=$HOME/.cache/Wallpaper.png

if [ -f $wallpaper_file ]; then
    swww img $wallpaper_file --transition-fps 60 --transition-type grow --transition-pos center --transition-duration 1
else
    swww img $(awk -F'=' "/^\\[Wallpaper\\]/{flag=1;next}/^\\[/{flag=0}flag && \$1~/LastWallpaper/{print \$2}" "$HOME/.config/swifty/config.ini" | tr -d '[:space:]') --transition-fps 60 --transition-type grow --transition-pos center --transition-duration 1
fi
