player: mpd
host: lyricsapi.vercel.app
ignoreErrors: true
timerInterval: 200
updateInterval: 2000
style:
  hAlignment: center
  before:
    background: ""
    foreground: "#787c99"
    bold: true
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: false
  current:
    background: ""
    foreground: "#ffffff"
    bold: true
    italic: false
    underline: true
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: "#787c99"
    bold: false
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: true
pipe:
  length: 0
  overflow: word
mpd:
  address: 127.0.0.1:6600
  password: ""
