#!/bin/sh

state=$(pactl get-sink-mute alsa_output.pci-0000_03_00.6.analog-stereo | awk '{print $2}')

if [ $state == "no" ]; then
    makoctl dismiss -a && notify-send -c volume-unmuted "Speaker Unmuted" "Current status: Unmuted"
elif [ $state == "yes" ]; then
    makoctl dismiss -a && notify-send -c volume-state "Speaker Muted" "Current status: Muted"
fi
