#!/bin/sh

status=$(playerctl --player=mpd status)

if [[ $status == "Playing" ]]; then
    makoctl dismiss -a && notify-send -c music -i $HOME/.local/share/albums/"$(mpc current --format "%title% - %artist%")".png "Now Playing" "$(mpc current --format %title%)"
else
    makoctl dismiss -a && notify-send -c music-paused "Music Paused" "Music player paused"
fi
