#!/bin/sh

status=$(playerctl --player=mpd status)

if [ $status = "Playing" ]; then
    makoctl dismiss -a && notify-send -c music -i $HOME/.local/share/albums/"$(mpc current --format "%title% - %artist%")".png "Playing" "$(mpc current --format %title%)"
else
    makoctl dismiss -a && notify-send -c music-paused -i $HOME/.local/share/icons/Music.png "Paused" "Song paused"
fi
