#!/bin/sh

state=$(pactl get-sink-mute alsa_output.pci-0000_03_00.6.analog-stereo | awk '{print $2}')

if [ $state == "no" ]; then
    makoctl dismiss -a && notify-send -c volume-unmuted -i $HOME/.local/share/icons/Sound.png "Unmuted" "Sound unmuted"
elif [ $state == "yes" ]; then
    makoctl dismiss -a && notify-send -c volume-state -i $HOME/.local/share/icons/Sound.png "Muted" "Sound muted"
fi
